apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: elijose55/database:latest
        env:
        - name: VPN_CERTIFICATE
          valueFrom:
            secretKeyRef:
              name: vpn-certificate
              key: password
        command: ["/bin/sh", "-c"]
        args: ["touch eli.ovpn &&  printenv VPN_CERTIFICATE > eli.ovpn && apt-get update && apt-get install -y openvpn && mkdir -p /dev/net && mknod /dev/net/tun c 10 200 && chmod 600 /dev/net/tun"] 
        ports:
        - containerPort: 8000
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
