#!/usr/bin/env python3
 
import argparse
import requests
import json

parser = argparse.ArgumentParser(description="Manipulador de Tarefas - APS2")

parser.add_argument('acao', action = 'store', choices=['adicionar', 'listar', 'buscar', 'apagar', 'atualizar'],
					help = 'Acao desejada para as Tarefas')


parser.add_argument('--nome', dest='nome', type=str, action='store',
					required = False, help='Nome da Tarefa')

parser.add_argument('--nivel', dest='nivel', type=int, action='store',
					required = False, help='Nivel da Tarefa')

parser.add_argument('--id', dest='id', type=int, action='store',
					required = False, help='Id da Tarefa')


def selector():

	if(arguments.acao == "listar"):
		r = requests.get(url)
		print(r.text)

	elif(arguments.acao == "adicionar"):
		if(arguments.nome == None or arguments.nivel == None):
			print("Acao invalida - Parametro faltando")
			return
		payload = {'nome': arguments.nome, 'nivel': arguments.nivel}
		r = requests.post(url, json=payload)
		print(r.text)

	elif(arguments.acao == "buscar"):
		par_url = url + '/' + str(arguments.id)
		r = requests.get(par_url)
		print(r.text)

	elif(arguments.acao == "apagar"):
		par_url = url + '/' + str(arguments.id)
		r = requests.delete(par_url)
		print(r.text)

	elif(arguments.acao == "atualizar"):
		if(arguments.nome == None and arguments.nivel == None):
			print("Acao invalida - Parametro a ser atualizado faltando (nome, nivel)")
			return
		if(arguments.nome == None):
			payload = {"nivel": arguments.nivel}
		if(arguments.nivel == None):
			payload = {"nome": arguments.nome}
		par_url = url + '/' + str(arguments.id)
		r = requests.put(par_url, json=payload)
		print(r.text)


'''
– /Tarefa/ - GET: lista todas as tarefas do dicionário.
– /Tarefa/ - POST: Adiciona uma tarefa.
– /Tarefa/<id> - GET: lista a tarefa com o determinado id.
– /Tarefa/<id> - PUT: atualiza uma tarefa com o determinado id.
– /Tarefa/<id> - DELETE: apaga a tarefa com o determinado id.
'''


'''
f = open('./ip.txt')
ip = f.readline()
f.close()
API_PATH =  "http://{0}:8888/task".format(ip)
'''

url = "http://127.0.0.1:5000/Tarefa"


arguments = parser.parse_args()

selector()

