apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: elijose55/database:latest
        ports:
        - containerPort: 8000
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
